services:
  web:
    image: prope:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    platform: linux/amd64
    image: mysql:lts
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8091:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mysql-phpmyadmin
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8092:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
  app-network:


volumes:
  dbdata:
